name: cores_{{package_name.snakeCase()}}
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.4.1

dev_dependencies:
  yumemi_lints: ^2.0.0
  test: ^1.24.0
